HotelTest/Controllers/AuthController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HotelTest.Models;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace HotelTest.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public AuthController()
            : this(Startup.UserManagerFactory.Invoke())
        {
        }

        public AuthController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public ActionResult LogIn(string returnUrl)
        {
            var model = new LogInModel();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> LogIn(LogInModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userManager.FindAsync(model.Email, model.Password);

            if (user != null)
            {
                var identity = await _userManager.CreateIdentityAsync(
                    user, DefaultAuthenticationTypes.ApplicationCookie);

                GetAuthenticationManager().SignIn(identity);

                return RedirectToAction("Index","Home");
            }

            // user authN failed
            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = new AppUser
            {
                UserName = model.Email,
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await SignIn(user);
                return RedirectToAction("index", "home");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

            return View();
        }

        private async Task SignIn(AppUser user)
        {
            var identity = await _userManager.CreateIdentityAsync(
                user, DefaultAuthenticationTypes.ApplicationCookie);
            GetAuthenticationManager().SignIn(identity);
        }

        private IAuthenticationManager GetAuthenticationManager()
        {
            return Request.GetOwinContext().Authentication;
        }

        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("index", "home");
            }

            return returnUrl;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _userManager != null)
            {
                _userManager.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

HotelTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="container">

    <div>
        @{ Html.RenderPartial("_MainMenuPartial"); }
    </div>
@RenderBody()

@Scripts.Render("~/bundles/jquery")
@RenderSection("scripts", required: false)
</div>
</body>
</html>

HotelTest/Views/Shared/_MainMenuPartial.cshtml
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Hotels</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li>@Html.ActionLink("Hotels","Index","Home", null,null)</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Login","LogIn","Auth")</li>
        <li>@Html.ActionLink("Register","Register","Auth")</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

HotelTest/Views/Shared/_entytiFieldListPartial.cshtml
@model IEnumerable<HotelTest.ViewModels.FieldEntity.RenderedFieldEntityViewModel>

@foreach (var renderedFieldEntityViewModel in Model)
{
  <div class="field field-@renderedFieldEntityViewModel.ID">@Html.Raw(renderedFieldEntityViewModel.RenderedField)</div>
}

HotelTest/Views/Shared/_fileUploadPartial.cshtml
@model HotelTest.Infrastructure.FileUploadModel

@Html.BeginForm("FileUpload","Home",FormMethod.Post, new { enctype = "multipart/form-data" }){

@Html.HiddenFor(x =>x.EntityTypeId)
@Html.HiddenFor(x =>x.EntityId)
<input type="file" name="files" multiple/>
<input type="submit" value="submit"/>

}

HotelTest/Views/Shared/_imageListPartial.cshtml
@model IEnumerable<HotelTest.Models.MediaFile>


@foreach (var mediaFile in Model)
{

<div>
    <img src="@mediaFile.Location" alt="@mediaFile.Name"/>
</div>
  
}